[workspace]
members = ["host", "guest-runtime", "apis", "nar-to-erofs", "nix-cache", "nix-drv"]
resolver = "3"

[patch.crates-io]
alioth = { path = "../alioth/alioth" }
erofs-builder = { path = "../erofs-rs" }

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
alioth = "0.12"
anyhow = "1"
arcbox-ext4 = "0.1"
backhand = "0.25"
bytes = "1"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
erofs-builder = "0.2"
flate2 = "1"
flume = "0.12"
futures = "0.3"
libc = "0.2"
log = "0.4"
mio = "1.2.2"
nix = { version = "0.31", features = ["fs", "mount", "reboot"] }
oci-spec = "0.10"
pid1 = "0.1"
postcard = { version = "1", default-features = false, features = ["use-std", "alloc"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tar = "0.4"
tokio-tar = "0.3"
tarpc = { version = "0.36", features = ["serde-transport"] }
tokio = { version = "1", features = ["rt", "macros", "io-util", "net", "time"] }
tokio-serde = { version = "0.9", default-features = false }
tokio-vsock = "0.7"
apis = { path = "apis" }
base64 = "0.22"
nix-drv = { path = "nix-drv" }
nar-to-erofs = { path = "nar-to-erofs" }
nix-cache = { path = "nix-cache" }
zstd = "0.13"
async-compression = { version = "0.4", features = ["tokio", "gzip", "xz", "zstd"] }
narinfo = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
sha2 = "0.10"
tempfile = "3"
thiserror = "2"
tokio-util = { version = "0.7", features = ["io"] }
